# Generated by Django 5.2 on 2025-04-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_No', models.PositiveIntegerField()),
                ('Patient_Name', models.CharField(max_length=50)),
                ('Next_Appointment_Date', models.DateField()),
                ('Last_Visit_Date', models.DateField()),
                ('Contact_No', models.PositiveIntegerField()),
            ],
        ),
    ]
