# Generated by Django 5.2 on 2025-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0002_patient_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='Contact_No',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='File_No',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
