# Generated by Django 5.2 on 2025-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0003_alter_patient_info_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('estimated_dob', models.BooleanField(default=False)),
                ('age_years', models.PositiveIntegerField(blank=True, null=True)),
                ('age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Third Gender')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_proof', models.CharField(blank=True, max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_person', models.CharField(max_length=150)),
                ('emergency_relation', models.CharField(blank=True, max_length=100)),
                ('emergency_mobile_number', models.CharField(max_length=15)),
                ('emergency_landline_number', models.CharField(blank=True, max_length=15)),
                ('permanent_address', models.TextField()),
                ('permanent_city', models.CharField(max_length=100)),
                ('permanent_pincode', models.CharField(max_length=10)),
                ('permanent_state_ut', models.CharField(max_length=100)),
                ('is_current_same_as_permanent', models.BooleanField(default=False)),
                ('current_address', models.TextField(blank=True)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('current_pincode', models.CharField(blank=True, max_length=10)),
                ('current_state_ut', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
