# Generated by Django 5.2 on 2025-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0004_patientbasicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbasicinfo',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientbasicinfo',
            name='file_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientbasicinfo',
            name='jehangir_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientbasicinfo',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientbasicinfo',
            name='patient_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientbasicinfo',
            name='primary_consultant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientbasicinfo',
            name='referral_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patientbasicinfo',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
