# Generated by Django 5.2 on 2025-04-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0005_patientbasicinfo_date_of_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbasicinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='patientbasicinfo',
            name='patient_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'A'), ('C', 'C')], max_length=255, null=True)),
                ('investigation_intervention_advised1', models.CharField(blank=True, max_length=255, null=True)),
                ('date_investigation_intervention_done1', models.DateField(blank=True, null=True)),
                ('investigation_intervention_advised2', models.CharField(blank=True, max_length=255, null=True)),
                ('date_investigation_intervention_done2', models.DateField(blank=True, null=True)),
                ('investigation_intervention_advised3', models.CharField(blank=True, max_length=255, null=True)),
                ('date_investigation_intervention_done3', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pccm_website.patientbasicinfo')),
            ],
        ),
    ]
