# Generated by Django 5.2 on 2025-05-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0006_remove_patientbasicinfo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientinformationhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('annual_household_income', models.CharField(blank=True, choices=[('0-2.5', '0–2.5 Lakhs'), ('2.5-5', '2.5–5 Lakhs'), ('5-10', '5–10 Lakhs'), ('>10', '>10 Lakhs')], max_length=10, null=True)),
                ('supplement_taken', models.BooleanField()),
                ('supplement_type', models.CharField(blank=True, max_length=255, null=True)),
                ('supplement_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('supplement_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pccm_website.patientbasicinfo')),
            ],
        ),
    ]
