# Generated by Django 5.2 on 2025-05-21 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0007_patientinformationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformationhistory',
            name='alcohol_consumption_age_yrs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='alcohol_y_n',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='comments_alcohol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='comments_tobacco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='diet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='duration_alcohol_consumption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='duration_tobacco_consumption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='frequency_physical_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='other_deleterious_habits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='physical_activity_y_n',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='quantity_alcohol_per_week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='quantity_tobacco_per_week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='tobacco_consumption_age_yrs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='tobacco_exposure_modes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='tobacco_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='tobacco_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='tobacco_y_n',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='type_physical_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='clinical_examinatin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pccm_website.patientbasicinfo')),
            ],
        ),
    ]
