# Generated by Django 5.2 on 2025-05-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0008_patientinformationhistory_alcohol_consumption_age_yrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformationhistory',
            name='age_at_menarche_yrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='age_at_menopause_yrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='age_first_pregnancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='any_complications_during_pregnancy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='breast_feeding',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='complications_associated_with_menopause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='cycles_fertility_treatment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='date_last_menstrual_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='daughters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='details_birth_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='details_fertility_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='duration_birth_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='fertility_treatment_y_n',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='has_children',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='menopause_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='number_abortions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='number_conceptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='number_pregnancies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='period_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='sons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='success_fertility_treatment',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='type_birth_control_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='type_fertility_treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
