# Generated by Django 5.2 on 2025-05-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0009_patientinformationhistory_age_at_menarche_yrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformationhistory',
            name='current_breast_cancer_detected_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientinformationhistory',
            name='current_breast_cancer_detected_date',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='clinical_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_edema', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both'), ('absent', 'Absent')], max_length=15, null=True)),
                ('breast_size', models.CharField(blank=True, choices=[('Extra Small', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=15, null=True)),
                ('ptosis', models.CharField(blank=True, choices=[('grade1', 'Grade 1 (Mid)'), ('grade2', 'Grade 2 (Moderate)'), ('grade3', 'Grade 3 (Advanced)'), ('pseudoptosis', 'Pseudoptosis'), ('maldistribution', 'Parenchymal Maldistribution')], max_length=30, null=True)),
                ('bra_size', models.FloatField(blank=True, null=True)),
                ('bra_size_cup', models.CharField(blank=True, max_length=10, null=True)),
                ('lump_in_breast', models.CharField(blank=True, choices=[('definitely_palpable', 'Definitely Palpable'), ('vaguely_palpable', 'Vaguely Palpable'), ('diffuse', 'Diffuse'), ('no', 'No')], max_length=30, null=True)),
                ('mastitis_type', models.CharField(blank=True, choices=[('diffuse', 'Diffuse'), ('sectoral', 'Sectoral')], max_length=15, null=True)),
                ('tenderness', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both'), ('absent', 'Absent')], max_length=15, null=True)),
                ('nipple_retraction', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both'), ('absent', 'Absent')], max_length=15, null=True)),
                ('nipple_discharge', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both'), ('absent', 'Absent')], max_length=15, null=True)),
                ('nipple_discharge_type', models.CharField(blank=True, choices=[('serous', 'Serous'), ('milky', 'Milky'), ('brown', 'Brown'), ('bloody', 'Bloody')], max_length=15, null=True)),
                ('skin_change', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both'), ('absent', 'Absent')], max_length=15, null=True)),
                ('skin_change_type', models.TextField(blank=True, null=True)),
                ('location_right', models.TextField(blank=True, null=True)),
                ('location_left', models.TextField(blank=True, null=True)),
                ('lesion_category', models.CharField(blank=True, max_length=100, null=True)),
                ('location_picture', models.FileField(blank=True, null=True, upload_to='lesion_pictures/')),
                ('lump_size', models.CharField(blank=True, choices=[('<2', '< 2 cm'), ('2-5', '2–5 cm'), ('>5', '> 5 cm'), ('nil', 'Nil')], max_length=15, null=True)),
                ('lump_consistency', models.CharField(blank=True, choices=[('soft', 'Soft'), ('firm', 'Firm'), ('hard', 'Hard'), ('cystic', 'Cystic'), ('mobile', 'Mobile')], max_length=15, null=True)),
                ('sternal_notch_to_nipple_distance_cm', models.CharField(blank=True, max_length=15, null=True)),
                ('tumor_distance_from_nipple', models.CharField(blank=True, max_length=15, null=True)),
                ('distance_from_im_crease_lower_quadrant_tumor', models.CharField(blank=True, max_length=15, null=True)),
                ('skin_tethering', models.CharField(blank=True, max_length=50, null=True)),
                ('local_edema', models.CharField(blank=True, max_length=50, null=True)),
                ('tumor_breast_ratio', models.FloatField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pccm_website.patientbasicinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='clinical_examinatin',
        ),
    ]
