# Generated by Django 5.2 on 2025-05-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0010_patientinformationhistory_current_breast_cancer_detected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_axillary_nodes_fixity',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_axillary_nodes_location',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_axillary_nodes_number',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_axillary_nodes_size',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_supraclavicular_nodes_fixity',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_supraclavicular_nodes_location',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_supraclavicular_nodes_number',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='palpable_supraclavicular_nodes_size',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
    ]
