# Generated by Django 5.2 on 2025-05-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0011_clinical_examination_palpable_axillary_nodes_fixity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_examination',
            name='palpable_axillary_nodes_fixity',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_examination',
            name='palpable_axillary_nodes_location',
            field=models.TextField(blank=True, choices=[('<2', '< 2 cm'), ('2-5', '2–5 cm'), ('>5', '> 5 cm'), ('nil', 'Nil')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_examination',
            name='palpable_supraclavicular_nodes_fixity',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_examination',
            name='palpable_supraclavicular_nodes_location',
            field=models.TextField(blank=True, choices=[('<2', '< 2 cm'), ('2-5', '2–5 cm'), ('>5', '> 5 cm'), ('nil', 'Nil')], max_length=15, null=True),
        ),
    ]
