# Generated by Django 5.2 on 2025-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0012_alter_clinical_examination_palpable_axillary_nodes_fixity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_examination',
            name='palpable_axillary_nodes_location',
            field=models.TextField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both'), ('absent', 'Absent')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_examination',
            name='palpable_supraclavicular_nodes_location',
            field=models.TextField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both'), ('absent', 'Absent')], max_length=15, null=True),
        ),
    ]
