# Generated by Django 5.2 on 2025-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0014_alter_clinical_examination_palpable_axillary_nodes_fixity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical_examination',
            name='arm_circumfernce_cm',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='arm_to_elbow_cm',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='arm_volume_cc',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='consent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='contralateral_breast',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='diagnosis_and_advice_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='ecog',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='follow_up_advised',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='on_examination_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='provisional_diagnosis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_examination',
            name='status_of_the_disease',
            field=models.TextField(blank=True, null=True),
        ),
    ]
