# Generated by Django 5.2 on 2025-06-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0015_clinical_examination_arm_circumfernce_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_examination',
            name='consent',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('discussed', 'Discussed')], null=True),
        ),
        migrations.AlterField(
            model_name='clinical_examination',
            name='contralateral_breast',
            field=models.TextField(blank=True, choices=[('normal', 'Normal'), ('diffuse_mastitis', 'Diffuse Mastitis'), ('localised_mastitis', 'Localised Mastitis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_examination',
            name='follow_up_advised',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_examination',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
