# Generated by Django 5.2 on 2025-06-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccm_website', '0016_alter_clinical_examination_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical_examination',
            name='surgery_id',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_info', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pccm_website.patientbasicinfo')),
            ],
        ),
    ]
